// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MatchCreateSchema = {
    properties: {
        home_team_id: {
            type: 'string',
            format: 'uuid',
            title: 'Home Team Id'
        },
        away_team_id: {
            type: 'string',
            format: 'uuid',
            title: 'Away Team Id'
        }
    },
    type: 'object',
    required: ['home_team_id', 'away_team_id'],
    title: 'MatchCreate'
} as const;

export const MatchEventPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        match_id: {
            type: 'string',
            format: 'uuid',
            title: 'Match Id'
        },
        minute: {
            type: 'integer',
            title: 'Minute'
        },
        event_type: {
            '$ref': '#/components/schemas/MatchEventType'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        player_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player Id'
        },
        home_score: {
            type: 'integer',
            title: 'Home Score',
            default: 0
        },
        away_score: {
            type: 'integer',
            title: 'Away Score',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'match_id', 'minute', 'event_type', 'description'],
    title: 'MatchEventPublic'
} as const;

export const MatchEventTypeSchema = {
    type: 'string',
    enum: ['KICKOFF', 'ATTACK', 'SHOT', 'GOAL', 'SAVE', 'TACKLE', 'FOUL', 'HALFTIME', 'FULLTIME'],
    title: 'MatchEventType'
} as const;

export const MatchPublicSchema = {
    properties: {
        home_score: {
            type: 'integer',
            title: 'Home Score',
            default: 0
        },
        away_score: {
            type: 'integer',
            title: 'Away Score',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        universe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Universe Id'
        },
        home_team_id: {
            type: 'string',
            format: 'uuid',
            title: 'Home Team Id'
        },
        away_team_id: {
            type: 'string',
            format: 'uuid',
            title: 'Away Team Id'
        },
        status: {
            '$ref': '#/components/schemas/MatchStatus'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'universe_id', 'home_team_id', 'away_team_id', 'status'],
    title: 'MatchPublic'
} as const;

export const MatchPublicWithDetailsSchema = {
    properties: {
        home_score: {
            type: 'integer',
            title: 'Home Score',
            default: 0
        },
        away_score: {
            type: 'integer',
            title: 'Away Score',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        universe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Universe Id'
        },
        home_team_id: {
            type: 'string',
            format: 'uuid',
            title: 'Home Team Id'
        },
        away_team_id: {
            type: 'string',
            format: 'uuid',
            title: 'Away Team Id'
        },
        status: {
            '$ref': '#/components/schemas/MatchStatus'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        home_team: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TeamPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        away_team: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TeamPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        events: {
            items: {
                '$ref': '#/components/schemas/MatchEventPublic'
            },
            type: 'array',
            title: 'Events',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'universe_id', 'home_team_id', 'away_team_id', 'status'],
    title: 'MatchPublicWithDetails'
} as const;

export const MatchStatusSchema = {
    type: 'string',
    enum: ['PENDING', 'LIVE', 'FINISHED'],
    title: 'MatchStatus'
} as const;

export const MatchesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MatchPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MatchesPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PlayerCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        height: {
            type: 'number',
            title: 'Height'
        },
        weight: {
            type: 'number',
            title: 'Weight'
        },
        universe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Universe Id'
        }
    },
    type: 'object',
    required: ['name', 'height', 'weight', 'universe_id'],
    title: 'PlayerCreate'
} as const;

export const PlayerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        height: {
            type: 'number',
            title: 'Height'
        },
        weight: {
            type: 'number',
            title: 'Weight'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        universe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Universe Id'
        },
        team_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Team Id'
        },
        position: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/Position'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'height', 'weight', 'id', 'universe_id'],
    title: 'PlayerPublic'
} as const;

export const PlayerUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        height: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Height'
        },
        weight: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weight'
        }
    },
    type: 'object',
    title: 'PlayerUpdate'
} as const;

export const PlayersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PlayerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlayersPublic'
} as const;

export const PositionSchema = {
    type: 'string',
    enum: ['GOALIE', 'DEFENCE', 'OFFENCE'],
    title: 'Position'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TeamConfigurationRequestSchema = {
    properties: {
        defenders: {
            type: 'integer',
            title: 'Defenders',
            default: 2
        },
        attackers: {
            type: 'integer',
            title: 'Attackers',
            default: 2
        }
    },
    type: 'object',
    title: 'TeamConfigurationRequest'
} as const;

export const TeamPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        universe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Universe Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'universe_id'],
    title: 'TeamPublic'
} as const;

export const TeamPublicWithPlayersSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        universe_id: {
            type: 'string',
            format: 'uuid',
            title: 'Universe Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        players: {
            items: {
                '$ref': '#/components/schemas/PlayerPublic'
            },
            type: 'array',
            title: 'Players',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'id', 'universe_id'],
    title: 'TeamPublicWithPlayers'
} as const;

export const TeamsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TeamPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TeamsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UniverseCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'UniverseCreate'
} as const;

export const UniversePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'UniversePublic'
} as const;

export const UniverseUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'UniverseUpdate'
} as const;

export const UniversesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UniversePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UniversesPublic'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;