// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, MatchesSimulateMatchEndpointData, MatchesSimulateMatchEndpointResponse, MatchesReadMatchesData, MatchesReadMatchesResponse, MatchesReadMatchData, MatchesReadMatchResponse, MatchesStreamMatchEventsData, MatchesStreamMatchEventsResponse, PlayersReadPlayersData, PlayersReadPlayersResponse, PlayersCreatePlayerData, PlayersCreatePlayerResponse, PlayersReadPlayerData, PlayersReadPlayerResponse, PlayersUpdatePlayerData, PlayersUpdatePlayerResponse, PlayersDeletePlayerData, PlayersDeletePlayerResponse, PrivateCreateUserData, PrivateCreateUserResponse, TeamsReadTeamsData, TeamsReadTeamsResponse, TeamsReadTeamData, TeamsReadTeamResponse, TeamsDeleteTeamData, TeamsDeleteTeamResponse, TeamsGenerateTeamEndpointData, TeamsGenerateTeamEndpointResponse, UniversesReadUniversesData, UniversesReadUniversesResponse, UniversesCreateUniverseData, UniversesCreateUniverseResponse, UniversesReadUniverseData, UniversesReadUniverseResponse, UniversesUpdateUniverseData, UniversesUpdateUniverseResponse, UniversesDeleteUniverseData, UniversesDeleteUniverseResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class MatchesService {
    /**
     * Simulate Match Endpoint
     * Simulate a match between two teams. Creates the match, runs the
     * simulation engine, persists all events, and returns the completed match.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns MatchPublic Successful Response
     * @throws ApiError
     */
    public static simulateMatchEndpoint(data: MatchesSimulateMatchEndpointData): CancelablePromise<MatchesSimulateMatchEndpointResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/matches/simulate',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Matches
     * Retrieve matches, optionally filtered by universe.
     * @param data The data for the request.
     * @param data.universeId
     * @param data.skip
     * @param data.limit
     * @returns MatchesPublic Successful Response
     * @throws ApiError
     */
    public static readMatches(data: MatchesReadMatchesData = {}): CancelablePromise<MatchesReadMatchesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/matches/',
            query: {
                universe_id: data.universeId,
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Match
     * Get match by ID with team details and all events.
     * @param data The data for the request.
     * @param data.id
     * @returns MatchPublicWithDetails Successful Response
     * @throws ApiError
     */
    public static readMatch(data: MatchesReadMatchData): CancelablePromise<MatchesReadMatchResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/matches/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Stream Match Events
     * Stream match events via SSE for a live ticker experience.
     * Events are streamed with artificial delays to simulate real-time playback.
     * @param data The data for the request.
     * @param data.id
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static streamMatchEvents(data: MatchesStreamMatchEventsData): CancelablePromise<MatchesStreamMatchEventsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/matches/{id}/stream',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PlayersService {
    /**
     * Read Players
     * Retrieve players, optionally filtered by universe.
     * @param data The data for the request.
     * @param data.universeId
     * @param data.skip
     * @param data.limit
     * @returns PlayersPublic Successful Response
     * @throws ApiError
     */
    public static readPlayers(data: PlayersReadPlayersData = {}): CancelablePromise<PlayersReadPlayersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/players/',
            query: {
                universe_id: data.universeId,
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Player
     * Create new player.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns PlayerPublic Successful Response
     * @throws ApiError
     */
    public static createPlayer(data: PlayersCreatePlayerData): CancelablePromise<PlayersCreatePlayerResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/players/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Player
     * Get player by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns PlayerPublic Successful Response
     * @throws ApiError
     */
    public static readPlayer(data: PlayersReadPlayerData): CancelablePromise<PlayersReadPlayerResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/players/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Player
     * Update a player.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns PlayerPublic Successful Response
     * @throws ApiError
     */
    public static updatePlayer(data: PlayersUpdatePlayerData): CancelablePromise<PlayersUpdatePlayerResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/players/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Player
     * Delete a player.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deletePlayer(data: PlayersDeletePlayerData): CancelablePromise<PlayersDeletePlayerResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/players/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class TeamsService {
    /**
     * Read Teams
     * Retrieve teams, optionally filtered by universe.
     * @param data The data for the request.
     * @param data.universeId
     * @param data.skip
     * @param data.limit
     * @returns TeamsPublic Successful Response
     * @throws ApiError
     */
    public static readTeams(data: TeamsReadTeamsData = {}): CancelablePromise<TeamsReadTeamsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/teams/',
            query: {
                universe_id: data.universeId,
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Team
     * Get team by ID with players.
     * @param data The data for the request.
     * @param data.id
     * @returns TeamPublicWithPlayers Successful Response
     * @throws ApiError
     */
    public static readTeam(data: TeamsReadTeamData): CancelablePromise<TeamsReadTeamResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/teams/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Team
     * Delete a team.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteTeam(data: TeamsDeleteTeamData): CancelablePromise<TeamsDeleteTeamResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/teams/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Generate Team Endpoint
     * Generate a team by assigning random players from a universe to positions.
     * @param data The data for the request.
     * @param data.universeId
     * @param data.requestBody
     * @returns TeamPublicWithPlayers Successful Response
     * @throws ApiError
     */
    public static generateTeamEndpoint(data: TeamsGenerateTeamEndpointData): CancelablePromise<TeamsGenerateTeamEndpointResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/teams/generate',
            query: {
                universe_id: data.universeId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UniversesService {
    /**
     * Read Universes
     * Retrieve universes.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UniversesPublic Successful Response
     * @throws ApiError
     */
    public static readUniverses(data: UniversesReadUniversesData = {}): CancelablePromise<UniversesReadUniversesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/universes/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Universe
     * Create new universe.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UniversePublic Successful Response
     * @throws ApiError
     */
    public static createUniverse(data: UniversesCreateUniverseData): CancelablePromise<UniversesCreateUniverseResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/universes/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Universe
     * Get universe by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns UniversePublic Successful Response
     * @throws ApiError
     */
    public static readUniverse(data: UniversesReadUniverseData): CancelablePromise<UniversesReadUniverseResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/universes/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Universe
     * Update a universe.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns UniversePublic Successful Response
     * @throws ApiError
     */
    public static updateUniverse(data: UniversesUpdateUniverseData): CancelablePromise<UniversesUpdateUniverseResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/universes/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Universe
     * Delete a universe.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUniverse(data: UniversesDeleteUniverseData): CancelablePromise<UniversesDeleteUniverseResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/universes/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}