"""Add Match and MatchEvent models

Revision ID: 857345153061
Revises: f0ce6bc08f38
Create Date: 2026-03-15 17:03:33.660174

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '857345153061'
down_revision = 'f0ce6bc08f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('universe_id', sa.Uuid(), nullable=False),
    sa.Column('home_team_id', sa.Uuid(), nullable=False),
    sa.Column('away_team_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'LIVE', 'FINISHED', name='matchstatus'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['universe_id'], ['universe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matchevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('KICKOFF', 'ATTACK', 'SHOT', 'GOAL', 'SAVE', 'TACKLE', 'FOUL', 'HALFTIME', 'FULLTIME', name='matcheventtype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('player_id', sa.Uuid(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matchevent')
    op.drop_table('matches')
    # ### end Alembic commands ###
